services:
  aider:
    image: paulgauthier/aider

    tmpfs:
      - /tmp

    security_opt:
      - no-new-privileges:true

    volumes:
      - ${HOST_DIR:-.}:/project
      - ./AGENTS.md:/config/AGENTS.md:ro
      - ./.aider.conf.yml:/config/.aider.conf.yml:ro
      - ${USERPROFILE}/.gitconfig:/app/.gitconfig:ro
    
    working_dir: /project

    stdin_open: true
    tty: true

    environment:
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}